apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: auth-mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  MYSQL_USER: "auth_user"
  MYSQL_PASSWORD: "Aauth123"
