apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  labels:
    app: auth-mysql
data:
  init.sql: |
    USE auth;
    CREATE TABLE IF NOT EXISTS user (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );
    INSERT INTO user (email, password) VALUES ('gokul@gmail.com', 'gokul123')
    ON DUPLICATE KEY UPDATE email=email;
